apiVersion: 1
contactPoints:
  - orgId: 1
    name: stack-webhook
    receivers:
      - uid: pas-webhook
        type: webhook
        settings:
          url: $ALERT_WEBHOOK_URL
          httpMethod: POST
policies:
  - orgId: 1
    receiver: stack-webhook
    group_by: [alertname, service]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
